OP-558: Sylius 2 upgrade
BitBagCommerce/SyliusBlacklistPlugin pull request #71
Opened 2024-10-09 06:53 UTC by jkindly

2024-10-10 09:14 UTC, mpysiak commented on .github/workflows/build.yml
>                      - sylius: "~1.13.0"
```suggestion
```

2024-10-10 09:14 UTC, mpysiak commented on .github/workflows/coding_standard.yml
>            - sylius: ^1.13
```suggestion
```

remove all excludes

2024-10-10 09:14 UTC, mpysiak commented on composer.json
> +        "sylius-labs/polyfill-symfony-security": "^1.1",
```suggestion
```

2024-10-10 09:14 UTC, mpysiak commented on composer.json
> +        "sylius/grid-bundle": "^1.13.0-ALPHA.3",
```suggestion
        "sylius/grid-bundle": "^1.13.0",
```

2024-10-10 09:14 UTC, mpysiak commented on src/Resources/config/services/form.xml
> +            <argument type="service" id="sylius.address_comparator" />
this service will probably be changed in sylius 2.0.0 to sylius.comparator.address

2024-10-10 09:14 UTC, mpysiak commented on src/Resources/config/services/twig/component.xml
> +                    template="@BitBagSyliusBlacklistPlugin/BlacklistingRule/Admin/form.html.twig"
next alpha will allow setting components templates in hooks rather then in service definitions

2024-10-10 09:14 UTC, mpysiak commented on src/Resources/views/AutomaticBlacklistingConfiguration/Admin/form.html.twig
> +{% form_theme form '@BitBagSyliusBlacklistPlugin/Form/theme.html.twig' %}
I will suggest to change `views` directory to `templates`

2024-10-10 09:14 UTC, mpysiak commented on src/Twig/AutomaticBlacklistingConfigurationLabelsExtension.php
> +final class AutomaticBlacklistingConfigurationLabelsExtension extends AbstractExtension
```suggestion
final readonly class AutomaticBlacklistingConfigurationLabelsExtension extends AbstractExtension
```

2024-10-10 09:14 UTC, mpysiak commented on tests/Application/config/sylius/2.0/packages/security.yaml
> +        - { path: "%sylius.security.admin_regex%/_partial", role: ROLE_NO_ACCESS }
please check latest security configuration in sylius. This access_control is out

2024-10-10 09:14 UTC, mpysiak commented on tests/Application/package.json
>      "jquery": "^3.6.0",
there is no jquery in sylius anymore :)

2024-10-17 20:09 UTC, senghe reviewed
I've checked this, but I think @mpysiak review is more relevant than my

2024-10-17 20:09 UTC, senghe commented on src/Resources/config/services/twig/component.xml
> +                id="bitbag_sylius_blacklist_plugin.twig.component.automatic_blacklisting_configuration.form"
```suggestion
                id="bitbag.sylius_blacklist_plugin.twig.component.automatic_blacklisting_configuration.form"
```

For all services

2024-10-17 20:09 UTC, senghe commented on src/Resources/config/services/twig/component.xml
> +            />
I would use a formatting like below:

```suggestion
            <tag name="sylius.live_component"
                    key="sylius_admin:fraud_suspicion:form"
                    template="@BitBagSyliusBlacklistPlugin/FraudSuspicion/Admin/form.html.twig"
            />
```

2025-01-08 10:12 UTC, dariusz-rup commented on src/Twig/AutomaticBlacklistingConfigurationLabelsExtension.php
> +final class AutomaticBlacklistingConfigurationLabelsExtension extends AbstractExtension
![image](https://github.com/user-attachments/assets/e4460cc1-c8ab-4501-8c01-04d56d321e33)

2025-01-08 10:12 UTC, dariusz-rup commented on tests/Application/package.json
>      "jquery": "^3.6.0",
remove jquery

2025-01-08 10:13 UTC, dariusz-rup commented on .github/workflows/build.yml
>                      - sylius: "~1.13.0"
fixed

2025-01-08 10:13 UTC, dariusz-rup commented on .github/workflows/coding_standard.yml
>            - sylius: ^1.13
fixed

2025-01-08 10:13 UTC, dariusz-rup commented on src/Resources/config/services/twig/component.xml
> +            />
fixed

2025-01-08 12:11 UTC, dariusz-rup commented on src/Resources/views/AutomaticBlacklistingConfiguration/Admin/form.html.twig
> +{% form_theme form '@BitBagSyliusBlacklistPlugin/Form/theme.html.twig' %}
done

2025-01-19 19:57 UTC, senghe requested changes

2025-01-19 19:57 UTC, senghe commented on .github/workflows/build.yml
> +                sylius: [ "~v2.0.0-alpha.2" ]
We shouldn't use alpha.

2025-01-19 19:57 UTC, senghe commented on .github/workflows/build.yml
> +                symfony: [ "^6.4" ]
How about Symfony 7?

2025-01-19 19:57 UTC, senghe commented on .github/workflows/coding_standard.yml
> +        sylius: [ "~v2.0.0-alpha.2" ]
Bump

2025-01-19 19:57 UTC, senghe commented on composer.json
> +        "sylius/sylius": "~2.0",
Sylius and PHP versions should be placed on top of "require" section, for better readability.

2025-01-19 19:57 UTC, senghe commented on config/routing/admin/fraud_suspicion.yaml
> +sylius_admin_fraud_suspicion_show:
Why name of route has been changed?

2025-01-19 19:57 UTC, senghe commented on config/services/twig/component.xml
> +            <tag name="sylius.live_component.admin"
Inconsistent formatting in the file.

2025-01-19 19:57 UTC, senghe commented on config/services/twig/component.xml
> +                class="Sylius\Bundle\UiBundle\Twig\Component\ResourceFormComponent"
```suggestion
        <service id="bitbag.sylius_blacklist_plugin.twig.component.fraud_suspicion.form"
                      class="Sylius\Bundle\UiBundle\Twig\Component\ResourceFormComponent"
```
would be better

2025-01-19 19:57 UTC, senghe commented on config/workflow/customer.yaml
> +
```suggestion
```

2025-01-19 19:57 UTC, senghe commented on spec/StateResolver/CustomerStateResolverSpec.php
> -/*
Why OS header has been removed?

2025-01-19 19:57 UTC, senghe commented on src/Checker/FraudSuspicion/FraudSuspicionActionEligibilityChecker.php
> -        if ((int) $lastFraudSuspicionsOfCustomer >= $automaticBlacklistingConfiguration->getPermittedFraudSuspicionsNumber()) {
Is this change relevant?

2025-01-19 19:57 UTC, senghe commented on src/Menu/FraudPreventionMenuBuilder.php
> -            ->setLabelAttribute('icon', 'hand paper')
Why you removed the icons?

2025-01-19 19:57 UTC, senghe commented on src/Resolver/SuspiciousOrderResolver.php
> +        private ServiceRegistryInterface $serviceRegistry,
everywhere for all services I would also put `readonly` keyword

2025-01-19 19:57 UTC, senghe commented on src/Validator/Constraints/Checkout/CheckoutAddressTypeValidator.php
> +        if (null == $customer) {
=== ?

2025-01-19 19:57 UTC, senghe commented on tests/Application/config/packages/_sylius.yaml
> +    - { resource: "@SyliusPayumBundle/Resources/config/app/config.yaml" }
Do we need payum here?

2025-01-19 19:57 UTC, senghe commented on tests/Application/config/packages/security.yaml
> +    #        - { path: "%sylius.security.api_user_account_regex%/.*", role: ROLE_USER }
What's this?

2025-01-19 19:57 UTC, senghe commented on tests/Application/config/packages/twig.yaml
> +#        - '@SyliusUi/Form/theme.html.twig'
Bump

2025-01-19 19:57 UTC, senghe commented on tests/Application/config/routes/sylius_shop.yaml
> +#    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"
:upside_down_face:

2025-01-19 19:57 UTC, senghe commented on tests/Application/config/sylius/2.0/packages/_sylius.yaml
> +#    sylius_refund_refund_payment: '%test_sylius_state_machine_adapter%'
:face_holding_back_tears:

2025-01-19 19:57 UTC, senghe commented on tests/Application/config/sylius/2.0/packages/security.yaml
> +security:
I do not get, why we have doubled configs, i.e. `tests/Application/config/packages/security.yaml` and the current one?

2025-01-19 19:57 UTC, senghe commented on tests/Application/templates/bundles/SyliusAdminBundle/order/show/content/header/title_block/actions.html.twig
> +{#{% from '@SyliusAdmin/shared/helper/icon.html.twig' import icon %}#}
:fire:

2025-01-22 08:17 UTC, dariusz-rup commented on tests/Application/config/packages/_sylius.yaml
> +    - { resource: "@SyliusPayumBundle/Resources/config/app/config.yaml" }
if i remove it, i got error:

![image](https://github.com/user-attachments/assets/836e8106-1b2e-4316-8bd4-6720c3a212f0)

2025-01-22 08:18 UTC, dariusz-rup commented on src/Menu/FraudPreventionMenuBuilder.php
> -            ->setLabelAttribute('icon', 'hand paper')
![image](https://github.com/user-attachments/assets/1b9c041d-469c-4cbc-89bc-27cfca59fd24)
in the new sylius, haven't the icons in child elements been removed? if so, there is no point in adding them in the code because they won't be displayed anyway

2025-01-22 08:18 UTC, dariusz-rup commented on config/routing/admin/fraud_suspicion.yaml
> +sylius_admin_fraud_suspicion_show:
![image](https://github.com/user-attachments/assets/dc749abb-fd78-444b-9810-074e497c4b20)
previous developer made the change

2025-01-23 14:37 UTC, dariusz-rup commented on config/routing/admin/fraud_suspicion.yaml
> +sylius_admin_fraud_suspicion_show:
revert to previous route make error:
Variable "hookable_metadata" does not exist.

I will describe change in update.md

2025-01-27 08:27 UTC, dariusz-rup commented on config/config.yaml
> +    - { resource: "workflow.yaml" }
The configuration in customer.xml has been rewritten from winzou to symfony workflow, so why should we keep winzou configuration?

![image](https://github.com/user-attachments/assets/bf37e206-d083-4fc6-8aec-878ac87f9b73)

2025-01-28 08:22 UTC, dariusz-rup commented on src/Validator/Constraints/Checkout/CheckoutAddressTypeValidator.php
> +        /** @var CustomerInterface|null $customer */
yes, because without it phpstan reports errors

2025-01-29 07:39 UTC, senghe requested changes

2025-01-29 07:39 UTC, senghe commented on UPGRADE-2.0.md
> +# UPGRADE FROM 1.X TO 2.0
Is this file complete?

2025-01-29 07:39 UTC, senghe commented on config/workflow/customer.yaml
> +framework:
I'm wondering if we should use values instead of constands. The file would be more readable I think.

2025-01-29 07:39 UTC, senghe commented on src/Converter/FraudSuspicionCommonModelConverter.php
> +                'order' => $fraudSuspicion->getOrder(),
I would use a DTO instead of array

2025-01-29 07:39 UTC, senghe commented on src/Processor/AutomaticBlacklistingRulesProcessor.php
> +        private FraudSuspicionActionEligibilityCheckerInterface $fraudSuspicionActionEligibilityChecker,
Why they're not readonly?

2025-01-29 07:39 UTC, senghe commented on src/StateResolver/CustomerStateResolver.php
> +        $this->workflow->apply($customer, 'blacklisting');
Here I think you could use constant instead of 'blacklisting'

2025-01-29 09:39 UTC, dariusz-rup commented on config/workflow/customer.yaml
> +framework:
According to the Sylius documentation ([State Machine](https://docs.sylius.com/the-book/architecture/state-machine)), using constants is the recommended approach. It ensures consistency and reduces the risk of typos in state names.

However, I have slightly adjusted the formatting to improve readability.

2025-03-03 06:24 UTC, senghe commented
Build fails because of today's Sylius issue with new version of tabler. I'm merging this anyway, as the build worked before changing the README.md file.

2025-03-03 06:24 UTC, merged